### ISSUE TITLE
Bug: Setting the IPs of newer HAProxy versions fails with nbproc > 1

### ISSUE THREAD

**Issue by peterfroehlich** [unixsurfer/haproxyadmin#14] opened 2018-09-19 12:12 UTC
I ran into a problem setting the IP of servers, running with nbproc > 1. It seems HAProxy syncs the changes by itself over the processes, so that the outputs of the socket writes differ. I confirmed this with HAProxy v 1.7.11 and 1.8.6 on Centos 7: 

```
Traceback (most recent call last):
  File "namerd-haproxy.py", line 270, in <module>
    main()
  File "namerd-haproxy.py", line 262, in main
    schedule["check"]()
  File "namerd-haproxy.py", line 194, in check_namerd
    haproxy_servers[target_haproxy_backend].setaddress(new_address) #, new_port)
  File "/vagrant/haproxyadmin/server.py", line 146, in setaddress
    return compare_values(values)
  File "/vagrant/haproxyadmin/utils.py", line 271, in compare_values
    raise IncosistentData(values)
haproxyadmin.exceptions.IncosistentData: Received different data per HAProxy process
```
The 'values' variable in 'utils/compare_values' had the following content: 

> [(1, "IP changed from '127.0.0.1' to '10.10.26.114' by 'stats socket command'"), (1, "no need to change the addr by 'stats socket command'"), (1, "no need to change the addr by 'stats socket command'"), (1, "no need to change the addr by 'stats socket command'")] 

Used HAProxy config: 
```
global
    log         127.0.0.1 local2
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon
    nbproc      4
    stats socket /run/haproxy/1.sock mode 0744 level admin process 1
    stats socket /run/haproxy/2.sock mode 0744 level admin process 2
    stats socket /run/haproxy/3.sock mode 0744 level admin process 3
    stats socket /run/haproxy/4.sock mode 0744 level admin process 4

defaults
    mode http

frontend  main
    bind *:5000
    default_backend             app

backend app
    balance     roundrobin
    server  app1 127.0.0.1:80 check
```

I tested the following on the command line to see if the IP propagates by itself through all HAProxy processes: 

```
 [root@namerd-haproxy00 vagrant]# echo "show servers state" | socat /run/haproxy/1.sock -
 1
 # be_id be_name srv_id srv_name srv_addr srv_op_state srv_admin_state srv_uweight srv_iweight srv_time_since_last_change srv_check_status srv_check_result srv_check_health srv_check_state srv_agent_state bk_f_forced_id srv_f_forced_id srv_fqdn srv_port
 7 app 1 app1 10.10.26.114 0 0 1 1 1574 8 2 0 6 0 0 0 - 80
 
 [root@namerd-haproxy00 vagrant]# echo "show servers state" | socat /run/haproxy/2.sock -
 1
 # be_id be_name srv_id srv_name srv_addr srv_op_state srv_admin_state srv_uweight srv_iweight srv_time_since_last_change srv_check_status srv_check_result srv_check_health srv_check_state srv_agent_state bk_f_forced_id srv_f_forced_id srv_fqdn srv_port
 7 app 1 app1 10.10.26.114 0 0 1 1 1576 8 2 0 6 0 0 0 - 80
 
 [root@namerd-haproxy00 vagrant]# echo "set server app/app1 addr 10.10.10.10 port 3333" | socat /run/haproxy/1.sock -
 IP changed from '10.10.26.114' to '10.10.10.10', port changed from '80' to '3333' by 'stats socket command'
 
 [root@namerd-haproxy00 vagrant]# echo "show servers state" | socat /run/haproxy/2.sock -
 1
 # be_id be_name srv_id srv_name srv_addr srv_op_state srv_admin_state srv_uweight srv_iweight srv_time_since_last_change srv_check_status srv_check_result srv_check_health srv_check_state srv_agent_state bk_f_forced_id srv_f_forced_id srv_fqdn srv_port
 7 app 1 app1 10.10.10.10 0 0 1 1 1594 7 2 0 6 0 0 0 - 3333
 
 [root@namerd-haproxy00 vagrant]# echo "show servers state" | socat /run/haproxy/3.sock -
 1
 # be_id be_name srv_id srv_name srv_addr srv_op_state srv_admin_state srv_uweight srv_iweight srv_time_since_last_change srv_check_status srv_check_result srv_check_health srv_check_state srv_agent_state bk_f_forced_id srv_f_forced_id srv_fqdn srv_port
 7 app 1 app1 10.10.10.10 0 0 1 1 1602 7 0 0 7 0 0 0 - 3333
```

**Comment by unixsurfer** [comment] 2019-04-10 13:55
```

**Comment by unixsurfer** [comment] 2019-04-10 13:59
I can't reproduce this with HAProxy version `1.8.19-a3cfe8-8`, see below where each process returned the same output
```
haproxytool haproxy -D /run/haproxy -c 'show stat'|grep srv1_all
backend_all,srv1_all,0,0,0,0,,0,0,0,,0,,0,0,0,0,DOWN,1,1,0,1,1,572,572,,4,3,1,,0,,2,0,,0,L4CON,,0,0,0,0,0,0,0,,,,,0,0,,,,,-1,Connection refused,,0,0,0,0,,,,Layer4 connection problem,,3,2,0,,,,127.0.0.1:8001,,http,,,,,,,,
backend_all,srv1_all,0,0,0,0,,0,0,0,,0,,0,0,0,0,DOWN,1,1,0,1,1,572,572,,3,3,1,,0,,2,0,,0,L4CON,,0,0,0,0,0,0,0,,,,,0,0,,,,,-1,Connection refused,,0,0,0,0,,,,Layer4 connection problem,,3,2,0,,,,127.0.0.1:8001,,http,,,,,,,,
backend_all,srv1_all,0,0,0,0,,0,0,0,,0,,0,0,0,0,DOWN,1,1,0,1,1,572,572,,2,3,1,,0,,2,0,,0,L4CON,,0,0,0,0,0,0,0,,,,,0,0,,,,,-1,Connection refused,,0,0,0,0,,,,Layer4 connection problem,,3,2,0,,,,127.0.0.1:8001,,http,,,,,,,,
backend_all,srv1_all,0,0,0,0,,0,0,0,,0,,0,0,0,0,DOWN,1,1,0,1,1,572,572,,1,3,1,,0,,2,0,,0,L4CON,,0,0,0,0,0,0,0,,,,,0,0,,,,,-1,Connection refused,,0,0,0,0,,,,Layer4 connection problem,,3,2,0,,,,127.0.0.1:8001,,http,,,,,,,,

(python36) user at host in ~/repo/github/haproxytool on (master *$ u=)
haproxytool haproxy -D /run/haproxy -c 'set server backend_all/srv1_all addr 127.0.0.2'
Process number: 4
IP changed from '127.0.0.1' to '127.0.0.2' by 'stats socket command'
Process number: 3
IP changed from '127.0.0.1' to '127.0.0.2' by 'stats socket command'
Process number: 2
IP changed from '127.0.0.1' to '127.0.0.2' by 'stats socket command'
Process number: 1
IP changed from '127.0.0.1' to '127.0.0.2' by 'stats socket command'

(python36) user at host in ~/repo/github/haproxytool on (master *$ u=)
haproxytool haproxy -D /run/haproxy -c 'show stat'|grep srv1_all
backend_all,srv1_all,0,0,0,0,,0,0,0,,0,,0,0,0,0,DOWN,1,1,0,1,1,689,689,,4,3,1,,0,,2,0,,0,L4CON,,0,0,0,0,0,0,0,,,,,0,0,,,,,-1,Connection refused,,0,0,0,0,,,,Layer4 connection problem,,3,2,0,,,,127.0.0.2:8001,,http,,,,,,,,
backend_all,srv1_all,0,0,0,0,,0,0,0,,0,,0,0,0,0,DOWN,1,1,0,1,1,689,689,,3,3,1,,0,,2,0,,0,L4CON,,0,0,0,0,0,0,0,,,,,0,0,,,,,-1,Connection refused,,0,0,0,0,,,,Layer4 connection problem,,3,2,0,,,,127.0.0.2:8001,,http,,,,,,,,
backend_all,srv1_all,0,0,0,0,,0,0,0,,0,,0,0,0,0,DOWN,1,1,0,1,1,689,689,,2,3,1,,0,,2,0,,0,L4CON,,0,0,0,0,0,0,0,,,,,0,0,,,,,-1,Connection refused,,0,0,0,0,,,,Layer4 connection problem,,3,2,0,,,,127.0.0.2:8001,,http,,,,,,,,
backend_all,srv1_all,0,0,0,0,,0,0,0,,0,,0,0,0,0,DOWN,1,1,0,1,1,689,689,,1,3,1,,0,,2,0,,0,L4CON,,0,0,0,0,0,0,0,,,,,0,0,,,,,-1,Connection refused,,0,0,0,0,,,,Layer4 connection problem,,3,2,0,,,,127.0.0.2:8001,,http,,,,,,,,
(python36) pparissis at poseidonas in ~/repo/github/haproxytool on (master *$ u=)
```

**Comment by unixsurfer** [comment] 2019-04-11 13:52
Closing as I can't reproduce it and during the development of https://github.com/unixsurfer/haproxyadmin/commit/bcc1c3dd2e3dd4d32d50e8e3ed2e09cf9d4d8cb2

**Closed as completed by unixsurfer** 2019-04-11 13:52 UTC
